apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-platform
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: devops-platform

  template:
    metadata:
      labels:
        app: devops-platform

    spec:
      containers:

      - name: flask-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:

        - containerPort: {{ .Values.service.targetPort }}
